/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "github.com/vmware-tanzu/vm-operator-api/api/v1alpha1"
	vmopv1alpha1 "k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/vmop/applyconfiguration/vmop/v1alpha1"
)

// FakeVirtualMachineSetResourcePolicies implements VirtualMachineSetResourcePolicyInterface
type FakeVirtualMachineSetResourcePolicies struct {
	Fake *FakeVmoperatorV1alpha1
	ns   string
}

var virtualmachinesetresourcepoliciesResource = v1alpha1.SchemeGroupVersion.WithResource("virtualmachinesetresourcepolicies")

var virtualmachinesetresourcepoliciesKind = v1alpha1.SchemeGroupVersion.WithKind("VirtualMachineSetResourcePolicy")

// Get takes name of the virtualMachineSetResourcePolicy, and returns the corresponding virtualMachineSetResourcePolicy object, and an error if there is any.
func (c *FakeVirtualMachineSetResourcePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualmachinesetresourcepoliciesResource, c.ns, name), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// List takes label and field selectors, and returns the list of VirtualMachineSetResourcePolicies that match those selectors.
func (c *FakeVirtualMachineSetResourcePolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineSetResourcePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualmachinesetresourcepoliciesResource, virtualmachinesetresourcepoliciesKind, c.ns, opts), &v1alpha1.VirtualMachineSetResourcePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualMachineSetResourcePolicyList{ListMeta: obj.(*v1alpha1.VirtualMachineSetResourcePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualMachineSetResourcePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineSetResourcePolicies.
func (c *FakeVirtualMachineSetResourcePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualmachinesetresourcepoliciesResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineSetResourcePolicy and creates it.  Returns the server's representation of the virtualMachineSetResourcePolicy, and an error, if there is any.
func (c *FakeVirtualMachineSetResourcePolicies) Create(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualmachinesetresourcepoliciesResource, c.ns, virtualMachineSetResourcePolicy), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// Update takes the representation of a virtualMachineSetResourcePolicy and updates it. Returns the server's representation of the virtualMachineSetResourcePolicy, and an error, if there is any.
func (c *FakeVirtualMachineSetResourcePolicies) Update(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualmachinesetresourcepoliciesResource, c.ns, virtualMachineSetResourcePolicy), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualMachineSetResourcePolicies) UpdateStatus(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineSetResourcePolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualmachinesetresourcepoliciesResource, "status", c.ns, virtualMachineSetResourcePolicy), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// Delete takes name of the virtualMachineSetResourcePolicy and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineSetResourcePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(virtualmachinesetresourcepoliciesResource, c.ns, name, opts), &v1alpha1.VirtualMachineSetResourcePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineSetResourcePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualmachinesetresourcepoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineSetResourcePolicyList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineSetResourcePolicy.
func (c *FakeVirtualMachineSetResourcePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualmachinesetresourcepoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied virtualMachineSetResourcePolicy.
func (c *FakeVirtualMachineSetResourcePolicies) Apply(ctx context.Context, virtualMachineSetResourcePolicy *vmopv1alpha1.VirtualMachineSetResourcePolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	if virtualMachineSetResourcePolicy == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(virtualMachineSetResourcePolicy)
	if err != nil {
		return nil, err
	}
	name := virtualMachineSetResourcePolicy.Name
	if name == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualmachinesetresourcepoliciesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeVirtualMachineSetResourcePolicies) ApplyStatus(ctx context.Context, virtualMachineSetResourcePolicy *vmopv1alpha1.VirtualMachineSetResourcePolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	if virtualMachineSetResourcePolicy == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(virtualMachineSetResourcePolicy)
	if err != nil {
		return nil, err
	}
	name := virtualMachineSetResourcePolicy.Name
	if name == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualmachinesetresourcepoliciesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.VirtualMachineSetResourcePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualMachineSetResourcePolicy), err
}
