/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/vmware-tanzu/vm-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	vmopv1alpha1 "k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/vmop/applyconfiguration/vmop/v1alpha1"
	scheme "k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/vmop/clientset/versioned/scheme"
)

// VirtualMachineServicesGetter has a method to return a VirtualMachineServiceInterface.
// A group's client should implement this interface.
type VirtualMachineServicesGetter interface {
	VirtualMachineServices(namespace string) VirtualMachineServiceInterface
}

// VirtualMachineServiceInterface has methods to work with VirtualMachineService resources.
type VirtualMachineServiceInterface interface {
	Create(ctx context.Context, virtualMachineService *v1alpha1.VirtualMachineService, opts v1.CreateOptions) (*v1alpha1.VirtualMachineService, error)
	Update(ctx context.Context, virtualMachineService *v1alpha1.VirtualMachineService, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineService, error)
	UpdateStatus(ctx context.Context, virtualMachineService *v1alpha1.VirtualMachineService, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VirtualMachineService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VirtualMachineServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineService, err error)
	Apply(ctx context.Context, virtualMachineService *vmopv1alpha1.VirtualMachineServiceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineService, err error)
	ApplyStatus(ctx context.Context, virtualMachineService *vmopv1alpha1.VirtualMachineServiceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineService, err error)
	VirtualMachineServiceExpansion
}

// virtualMachineServices implements VirtualMachineServiceInterface
type virtualMachineServices struct {
	client rest.Interface
	ns     string
}

// newVirtualMachineServices returns a VirtualMachineServices
func newVirtualMachineServices(c *VmoperatorV1alpha1Client, namespace string) *virtualMachineServices {
	return &virtualMachineServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the virtualMachineService, and returns the corresponding virtualMachineService object, and an error if there is any.
func (c *virtualMachineServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineService, err error) {
	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VirtualMachineServices that match those selectors.
func (c *virtualMachineServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VirtualMachineServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested virtualMachineServices.
func (c *virtualMachineServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a virtualMachineService and creates it.  Returns the server's representation of the virtualMachineService, and an error, if there is any.
func (c *virtualMachineServices) Create(ctx context.Context, virtualMachineService *v1alpha1.VirtualMachineService, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineService, err error) {
	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a virtualMachineService and updates it. Returns the server's representation of the virtualMachineService, and an error, if there is any.
func (c *virtualMachineServices) Update(ctx context.Context, virtualMachineService *v1alpha1.VirtualMachineService, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineService, err error) {
	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(virtualMachineService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *virtualMachineServices) UpdateStatus(ctx context.Context, virtualMachineService *v1alpha1.VirtualMachineService, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineService, err error) {
	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(virtualMachineService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the virtualMachineService and deletes it. Returns an error if one occurs.
func (c *virtualMachineServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *virtualMachineServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualmachineservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched virtualMachineService.
func (c *virtualMachineServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineService, err error) {
	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied virtualMachineService.
func (c *virtualMachineServices) Apply(ctx context.Context, virtualMachineService *vmopv1alpha1.VirtualMachineServiceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineService, err error) {
	if virtualMachineService == nil {
		return nil, fmt.Errorf("virtualMachineService provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(virtualMachineService)
	if err != nil {
		return nil, err
	}
	name := virtualMachineService.Name
	if name == nil {
		return nil, fmt.Errorf("virtualMachineService.Name must be provided to Apply")
	}
	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *virtualMachineServices) ApplyStatus(ctx context.Context, virtualMachineService *vmopv1alpha1.VirtualMachineServiceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineService, err error) {
	if virtualMachineService == nil {
		return nil, fmt.Errorf("virtualMachineService provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(virtualMachineService)
	if err != nil {
		return nil, err
	}

	name := virtualMachineService.Name
	if name == nil {
		return nil, fmt.Errorf("virtualMachineService.Name must be provided to Apply")
	}

	result = &v1alpha1.VirtualMachineService{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("virtualmachineservices").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
