/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/vmware-tanzu/vm-operator-api/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	vmopv1alpha1 "k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/vmop/applyconfiguration/vmop/v1alpha1"
	scheme "k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/vmop/clientset/versioned/scheme"
)

// VirtualMachineSetResourcePoliciesGetter has a method to return a VirtualMachineSetResourcePolicyInterface.
// A group's client should implement this interface.
type VirtualMachineSetResourcePoliciesGetter interface {
	VirtualMachineSetResourcePolicies(namespace string) VirtualMachineSetResourcePolicyInterface
}

// VirtualMachineSetResourcePolicyInterface has methods to work with VirtualMachineSetResourcePolicy resources.
type VirtualMachineSetResourcePolicyInterface interface {
	Create(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.CreateOptions) (*v1alpha1.VirtualMachineSetResourcePolicy, error)
	Update(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineSetResourcePolicy, error)
	UpdateStatus(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.UpdateOptions) (*v1alpha1.VirtualMachineSetResourcePolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VirtualMachineSetResourcePolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VirtualMachineSetResourcePolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error)
	Apply(ctx context.Context, virtualMachineSetResourcePolicy *vmopv1alpha1.VirtualMachineSetResourcePolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error)
	ApplyStatus(ctx context.Context, virtualMachineSetResourcePolicy *vmopv1alpha1.VirtualMachineSetResourcePolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error)
	VirtualMachineSetResourcePolicyExpansion
}

// virtualMachineSetResourcePolicies implements VirtualMachineSetResourcePolicyInterface
type virtualMachineSetResourcePolicies struct {
	client rest.Interface
	ns     string
}

// newVirtualMachineSetResourcePolicies returns a VirtualMachineSetResourcePolicies
func newVirtualMachineSetResourcePolicies(c *VmoperatorV1alpha1Client, namespace string) *virtualMachineSetResourcePolicies {
	return &virtualMachineSetResourcePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the virtualMachineSetResourcePolicy, and returns the corresponding virtualMachineSetResourcePolicy object, and an error if there is any.
func (c *virtualMachineSetResourcePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VirtualMachineSetResourcePolicies that match those selectors.
func (c *virtualMachineSetResourcePolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineSetResourcePolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VirtualMachineSetResourcePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested virtualMachineSetResourcePolicies.
func (c *virtualMachineSetResourcePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a virtualMachineSetResourcePolicy and creates it.  Returns the server's representation of the virtualMachineSetResourcePolicy, and an error, if there is any.
func (c *virtualMachineSetResourcePolicies) Create(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineSetResourcePolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a virtualMachineSetResourcePolicy and updates it. Returns the server's representation of the virtualMachineSetResourcePolicy, and an error, if there is any.
func (c *virtualMachineSetResourcePolicies) Update(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(virtualMachineSetResourcePolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineSetResourcePolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *virtualMachineSetResourcePolicies) UpdateStatus(ctx context.Context, virtualMachineSetResourcePolicy *v1alpha1.VirtualMachineSetResourcePolicy, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(virtualMachineSetResourcePolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualMachineSetResourcePolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the virtualMachineSetResourcePolicy and deletes it. Returns an error if one occurs.
func (c *virtualMachineSetResourcePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *virtualMachineSetResourcePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched virtualMachineSetResourcePolicy.
func (c *virtualMachineSetResourcePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied virtualMachineSetResourcePolicy.
func (c *virtualMachineSetResourcePolicies) Apply(ctx context.Context, virtualMachineSetResourcePolicy *vmopv1alpha1.VirtualMachineSetResourcePolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	if virtualMachineSetResourcePolicy == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(virtualMachineSetResourcePolicy)
	if err != nil {
		return nil, err
	}
	name := virtualMachineSetResourcePolicy.Name
	if name == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy.Name must be provided to Apply")
	}
	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *virtualMachineSetResourcePolicies) ApplyStatus(ctx context.Context, virtualMachineSetResourcePolicy *vmopv1alpha1.VirtualMachineSetResourcePolicyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.VirtualMachineSetResourcePolicy, err error) {
	if virtualMachineSetResourcePolicy == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(virtualMachineSetResourcePolicy)
	if err != nil {
		return nil, err
	}

	name := virtualMachineSetResourcePolicy.Name
	if name == nil {
		return nil, fmt.Errorf("virtualMachineSetResourcePolicy.Name must be provided to Apply")
	}

	result = &v1alpha1.VirtualMachineSetResourcePolicy{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("virtualmachinesetresourcepolicies").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
