---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsphere-csi-node
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: vsphere-csi-node
  namespace: kube-system
  labels:
    k8s-app: vsphere-csi-node
spec:
  selector:
    matchLabels:
      k8s-app: vsphere-csi-node
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: vsphere-csi-node
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: vsphere-csi-node
      containers:
        - name: vsphere-csi-node
          image: gcr.io/cloud-provider-vsphere/vsphere-csi:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          env:
          - name: VSPHERE_KUBE_CONFIG
            value: "*"
          - name: CSI_ENDPOINT
            value: unix:///var/lib/csi/sockets/node/csi.sock
          - name: X_CSI_MODE
            value: "node"
          volumeMounts:
            - mountPath: /etc/kubernetes/pki
              name: k8s-certs
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certs
              readOnly: true
            - mountPath: /etc/kubernetes/controller-manager.conf
              name: kubeconfig
              readOnly: true
            - mountPath: /etc/cloud
              name: vsphere-config-volume
              readOnly: true
            - mountPath: /var/lib/csi/sockets/node
              name: socket-dir
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
          resources:
            requests:
              cpu: 200m
      hostNetwork: true
      volumes:
      - hostPath:
          path: /var/lib/csi/sockets/node
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /etc/kubernetes/pki
          type: DirectoryOrCreate
        name: k8s-certs
      - hostPath:
          path: /etc/ssl/certs
          type: DirectoryOrCreate
        name: ca-certs
      - hostPath:
          path: /etc/kubernetes/controller-manager.conf
          type: FileOrCreate
        name: kubeconfig
      - name: vsphere-config-volume
        configMap:
          name: cloud-config
      - name: pods-mount-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: device-dir
        hostPath:
          path: /dev
