/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineNamespaceLister.
type VirtualMachineNamespaceListerExpansion interface{}

// VirtualMachineClassListerExpansion allows custom methods to be added to
// VirtualMachineClassLister.
type VirtualMachineClassListerExpansion interface{}

// VirtualMachineImageListerExpansion allows custom methods to be added to
// VirtualMachineImageLister.
type VirtualMachineImageListerExpansion interface{}

// VirtualMachineServiceListerExpansion allows custom methods to be added to
// VirtualMachineServiceLister.
type VirtualMachineServiceListerExpansion interface{}

// VirtualMachineServiceNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineServiceNamespaceLister.
type VirtualMachineServiceNamespaceListerExpansion interface{}

// VirtualMachineSetResourcePolicyListerExpansion allows custom methods to be added to
// VirtualMachineSetResourcePolicyLister.
type VirtualMachineSetResourcePolicyListerExpansion interface{}

// VirtualMachineSetResourcePolicyNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineSetResourcePolicyNamespaceLister.
type VirtualMachineSetResourcePolicyNamespaceListerExpansion interface{}
