{{- $config := .Values.config -}}
{{- if .Values.global }}
{{- if .Values.global.config }}
{{- $config = mergeOverwrite (deepCopy .Values.config) .Values.global.config -}}
{{- end }}
{{- end }}
{{- if $config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name | default "cloud-config" }}
  labels:
    app: {{ template "cpi.name" . }}
    vsphere-cpi-infra: cloud-config
    component: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
data:
  vsphere.conf: |
    # Global properties in this section will be used for all specified vCenters unless overriden in VirtualCenter section.
    global:
      port: 443
      {{- if $config.thumbprint }}
      thumbprint: {{ $config.thumbprint }}
      {{- else if $config.caFile }}
      ca-file: {{ $config.caFile }}
      {{- else }}
      # set insecure-flag to true if the vCenter uses a self-signed cert
      insecureFlag: true
      {{- end }}
      # settings for using k8s secret
      secretName: {{ $config.secret.name }}
      secretNamespace: {{ .Release.Namespace }}

    # vcenter section
    vcenter:
      {{ $config.vcenter }}:
        server: {{ $config.vcenter }}
        datacenters:
          - {{ $config.datacenter }}

    # labels for regions and zones
    labels:
      region: {{ $config.region }}
      zone: {{ $config.zone }}
    {{- if or $config.nodes.internalNetworkSubnetCidr $config.nodes.externalNetworkSubnetCidr $config.nodes.internalVmNetworkName $config.nodes.externalVmNetworkName $config.nodes.excludeInternalNetworkSubnetCidr $config.nodes.excludeExternalNetworkSubnetCidr }}
    # nodes section for IP address selection
    nodes:
      # Select the first address within the provided subnet for the node Internal IP
      {{- if $config.nodes.internalNetworkSubnetCidr }}
      internalNetworkSubnetCidr: {{ $config.nodes.internalNetworkSubnetCidr }}
      {{- end }}

      # Select the first address within the provided subnet for the node External IP
      {{- if $config.nodes.externalNetworkSubnetCidr }}
      externalNetworkSubnetCidr: {{ $config.nodes.externalNetworkSubnetCidr }}
      {{- end }}

      # Select the first address on the VM network matching the provided name for the node Internal IP
      {{- if $config.nodes.internalVmNetworkName }}
      internalVmNetworkName: {{ $config.nodes.internalVmNetworkName }}
      {{- end }}

      # Select the first address on the VM network matching the provided name for the node External IP
      {{- if $config.nodes.externalVmNetworkName }}
      externalVmNetworkName: {{ $config.nodes.externalVmNetworkName }}
      {{- end }}

      # Never select Internal IP addresses within the provided subnet ranges (highest precedence)
      {{- if $config.nodes.excludeInternalNetworkSubnetCidr }}
      excludeInternalNetworkSubnetCidr: {{ $config.nodes.excludeInternalNetworkSubnetCidr }}
      {{- end }}

      # Never select External IP addresses within the provided subnet ranges (highest precedence)
      {{- if $config.nodes.excludeExternalNetworkSubnetCidr }}
      excludeExternalNetworkSubnetCidr: {{ $config.nodes.excludeExternalNetworkSubnetCidr }}
      {{- end }}
    {{- end }}
{{- end -}}
