/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VirtualMachineImageSpecApplyConfiguration represents an declarative configuration of the VirtualMachineImageSpec type for use
// with apply.
type VirtualMachineImageSpecApplyConfiguration struct {
	Type            *string                                           `json:"type,omitempty"`
	ImageSourceType *string                                           `json:"imageSourceType,omitempty"`
	ProductInfo     *VirtualMachineImageProductInfoApplyConfiguration `json:"productInfo,omitempty"`
	OSInfo          *VirtualMachineImageOSInfoApplyConfiguration      `json:"osInfo,omitempty"`
}

// VirtualMachineImageSpecApplyConfiguration constructs an declarative configuration of the VirtualMachineImageSpec type for use with
// apply.
func VirtualMachineImageSpec() *VirtualMachineImageSpecApplyConfiguration {
	return &VirtualMachineImageSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *VirtualMachineImageSpecApplyConfiguration) WithType(value string) *VirtualMachineImageSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithImageSourceType sets the ImageSourceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageSourceType field is set to the value of the last call.
func (b *VirtualMachineImageSpecApplyConfiguration) WithImageSourceType(value string) *VirtualMachineImageSpecApplyConfiguration {
	b.ImageSourceType = &value
	return b
}

// WithProductInfo sets the ProductInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProductInfo field is set to the value of the last call.
func (b *VirtualMachineImageSpecApplyConfiguration) WithProductInfo(value *VirtualMachineImageProductInfoApplyConfiguration) *VirtualMachineImageSpecApplyConfiguration {
	b.ProductInfo = value
	return b
}

// WithOSInfo sets the OSInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OSInfo field is set to the value of the last call.
func (b *VirtualMachineImageSpecApplyConfiguration) WithOSInfo(value *VirtualMachineImageOSInfoApplyConfiguration) *VirtualMachineImageSpecApplyConfiguration {
	b.OSInfo = value
	return b
}
