/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/vm-operator-api/api/v1alpha1"
)

// VirtualMachineMetadataApplyConfiguration represents an declarative configuration of the VirtualMachineMetadata type for use
// with apply.
type VirtualMachineMetadataApplyConfiguration struct {
	ConfigMapName *string                                   `json:"configMapName,omitempty"`
	Transport     *v1alpha1.VirtualMachineMetadataTransport `json:"transport,omitempty"`
}

// VirtualMachineMetadataApplyConfiguration constructs an declarative configuration of the VirtualMachineMetadata type for use with
// apply.
func VirtualMachineMetadata() *VirtualMachineMetadataApplyConfiguration {
	return &VirtualMachineMetadataApplyConfiguration{}
}

// WithConfigMapName sets the ConfigMapName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapName field is set to the value of the last call.
func (b *VirtualMachineMetadataApplyConfiguration) WithConfigMapName(value string) *VirtualMachineMetadataApplyConfiguration {
	b.ConfigMapName = &value
	return b
}

// WithTransport sets the Transport field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transport field is set to the value of the last call.
func (b *VirtualMachineMetadataApplyConfiguration) WithTransport(value v1alpha1.VirtualMachineMetadataTransport) *VirtualMachineMetadataApplyConfiguration {
	b.Transport = &value
	return b
}
