/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VirtualMachineImageStatusApplyConfiguration represents an declarative configuration of the VirtualMachineImageStatus type for use
// with apply.
type VirtualMachineImageStatusApplyConfiguration struct {
	Uuid                *string `json:"uuid,omitempty"`
	InternalId          *string `json:"internalId,omitempty"`
	PowerState          *string `json:"powerState,omitempty"`
	GuestOSCustomizable *bool   `json:"guestOsCustomizable,omitempty"`
}

// VirtualMachineImageStatusApplyConfiguration constructs an declarative configuration of the VirtualMachineImageStatus type for use with
// apply.
func VirtualMachineImageStatus() *VirtualMachineImageStatusApplyConfiguration {
	return &VirtualMachineImageStatusApplyConfiguration{}
}

// WithUuid sets the Uuid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uuid field is set to the value of the last call.
func (b *VirtualMachineImageStatusApplyConfiguration) WithUuid(value string) *VirtualMachineImageStatusApplyConfiguration {
	b.Uuid = &value
	return b
}

// WithInternalId sets the InternalId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalId field is set to the value of the last call.
func (b *VirtualMachineImageStatusApplyConfiguration) WithInternalId(value string) *VirtualMachineImageStatusApplyConfiguration {
	b.InternalId = &value
	return b
}

// WithPowerState sets the PowerState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PowerState field is set to the value of the last call.
func (b *VirtualMachineImageStatusApplyConfiguration) WithPowerState(value string) *VirtualMachineImageStatusApplyConfiguration {
	b.PowerState = &value
	return b
}

// WithGuestOSCustomizable sets the GuestOSCustomizable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuestOSCustomizable field is set to the value of the last call.
func (b *VirtualMachineImageStatusApplyConfiguration) WithGuestOSCustomizable(value bool) *VirtualMachineImageStatusApplyConfiguration {
	b.GuestOSCustomizable = &value
	return b
}
