/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// VirtualMachineClassHardwareApplyConfiguration represents an declarative configuration of the VirtualMachineClassHardware type for use
// with apply.
type VirtualMachineClassHardwareApplyConfiguration struct {
	Cpus   *int64             `json:"cpus,omitempty"`
	Memory *resource.Quantity `json:"memory,omitempty"`
}

// VirtualMachineClassHardwareApplyConfiguration constructs an declarative configuration of the VirtualMachineClassHardware type for use with
// apply.
func VirtualMachineClassHardware() *VirtualMachineClassHardwareApplyConfiguration {
	return &VirtualMachineClassHardwareApplyConfiguration{}
}

// WithCpus sets the Cpus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cpus field is set to the value of the last call.
func (b *VirtualMachineClassHardwareApplyConfiguration) WithCpus(value int64) *VirtualMachineClassHardwareApplyConfiguration {
	b.Cpus = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *VirtualMachineClassHardwareApplyConfiguration) WithMemory(value resource.Quantity) *VirtualMachineClassHardwareApplyConfiguration {
	b.Memory = &value
	return b
}
