/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VirtualMachineAdvancedOptionsApplyConfiguration represents an declarative configuration of the VirtualMachineAdvancedOptions type for use
// with apply.
type VirtualMachineAdvancedOptionsApplyConfiguration struct {
	DefaultVolumeProvisioningOptions *VirtualMachineVolumeProvisioningOptionsApplyConfiguration `json:"defaultVolumeProvisioningOptions,omitempty"`
	ChangeBlockTracking              *bool                                                      `json:"changeBlockTracking,omitempty"`
}

// VirtualMachineAdvancedOptionsApplyConfiguration constructs an declarative configuration of the VirtualMachineAdvancedOptions type for use with
// apply.
func VirtualMachineAdvancedOptions() *VirtualMachineAdvancedOptionsApplyConfiguration {
	return &VirtualMachineAdvancedOptionsApplyConfiguration{}
}

// WithDefaultVolumeProvisioningOptions sets the DefaultVolumeProvisioningOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultVolumeProvisioningOptions field is set to the value of the last call.
func (b *VirtualMachineAdvancedOptionsApplyConfiguration) WithDefaultVolumeProvisioningOptions(value *VirtualMachineVolumeProvisioningOptionsApplyConfiguration) *VirtualMachineAdvancedOptionsApplyConfiguration {
	b.DefaultVolumeProvisioningOptions = value
	return b
}

// WithChangeBlockTracking sets the ChangeBlockTracking field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChangeBlockTracking field is set to the value of the last call.
func (b *VirtualMachineAdvancedOptionsApplyConfiguration) WithChangeBlockTracking(value bool) *VirtualMachineAdvancedOptionsApplyConfiguration {
	b.ChangeBlockTracking = &value
	return b
}
