/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VsphereVolumeSourceApplyConfiguration represents an declarative configuration of the VsphereVolumeSource type for use
// with apply.
type VsphereVolumeSourceApplyConfiguration struct {
	Capacity  *v1.ResourceList `json:"capacity,omitempty"`
	DeviceKey *int             `json:"deviceKey,omitempty"`
}

// VsphereVolumeSourceApplyConfiguration constructs an declarative configuration of the VsphereVolumeSource type for use with
// apply.
func VsphereVolumeSource() *VsphereVolumeSourceApplyConfiguration {
	return &VsphereVolumeSourceApplyConfiguration{}
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *VsphereVolumeSourceApplyConfiguration) WithCapacity(value v1.ResourceList) *VsphereVolumeSourceApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithDeviceKey sets the DeviceKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceKey field is set to the value of the last call.
func (b *VsphereVolumeSourceApplyConfiguration) WithDeviceKey(value int) *VsphereVolumeSourceApplyConfiguration {
	b.DeviceKey = &value
	return b
}
