// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloudprovidervsphere.proto

package cloudprovidervsphere

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListNodesRequest struct {
	Vcenter              string   `protobuf:"bytes,1,opt,name=vcenter,proto3" json:"vcenter,omitempty"`
	Datacenter           string   `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesRequest) Reset()         { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()    {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b637d4c33cef7514, []int{0}
}

func (m *ListNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesRequest.Unmarshal(m, b)
}
func (m *ListNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesRequest.Marshal(b, m, deterministic)
}
func (m *ListNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesRequest.Merge(m, src)
}
func (m *ListNodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodesRequest.Size(m)
}
func (m *ListNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesRequest proto.InternalMessageInfo

func (m *ListNodesRequest) GetVcenter() string {
	if m != nil {
		return m.Vcenter
	}
	return ""
}

func (m *ListNodesRequest) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

type Node struct {
	Vcenter              string   `protobuf:"bytes,1,opt,name=vcenter,proto3" json:"vcenter,omitempty"`
	Datacenter           string   `protobuf:"bytes,2,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Dnsnames             []string `protobuf:"bytes,4,rep,name=dnsnames,proto3" json:"dnsnames,omitempty"`
	Addresses            []string `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Uuid                 string   `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_b637d4c33cef7514, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetVcenter() string {
	if m != nil {
		return m.Vcenter
	}
	return ""
}

func (m *Node) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetDnsnames() []string {
	if m != nil {
		return m.Dnsnames
	}
	return nil
}

func (m *Node) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Node) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ListNodesReply struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesReply) Reset()         { *m = ListNodesReply{} }
func (m *ListNodesReply) String() string { return proto.CompactTextString(m) }
func (*ListNodesReply) ProtoMessage()    {}
func (*ListNodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b637d4c33cef7514, []int{2}
}

func (m *ListNodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesReply.Unmarshal(m, b)
}
func (m *ListNodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesReply.Marshal(b, m, deterministic)
}
func (m *ListNodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesReply.Merge(m, src)
}
func (m *ListNodesReply) XXX_Size() int {
	return xxx_messageInfo_ListNodesReply.Size(m)
}
func (m *ListNodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesReply proto.InternalMessageInfo

func (m *ListNodesReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ListNodesReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ListNodesRequest)(nil), "cloudprovidervsphere.ListNodesRequest")
	proto.RegisterType((*Node)(nil), "cloudprovidervsphere.Node")
	proto.RegisterType((*ListNodesReply)(nil), "cloudprovidervsphere.ListNodesReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CloudProviderVsphereClient is the client API for CloudProviderVsphere service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CloudProviderVsphereClient interface {
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesReply, error)
}

type cloudProviderVsphereClient struct {
	cc *grpc.ClientConn
}

func NewCloudProviderVsphereClient(cc *grpc.ClientConn) CloudProviderVsphereClient {
	return &cloudProviderVsphereClient{cc}
}

func (c *cloudProviderVsphereClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesReply, error) {
	out := new(ListNodesReply)
	err := c.cc.Invoke(ctx, "/cloudprovidervsphere.CloudProviderVsphere/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudProviderVsphereServer is the server API for CloudProviderVsphere service.
type CloudProviderVsphereServer interface {
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesReply, error)
}

func RegisterCloudProviderVsphereServer(s *grpc.Server, srv CloudProviderVsphereServer) {
	s.RegisterService(&_CloudProviderVsphere_serviceDesc, srv)
}

func _CloudProviderVsphere_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudProviderVsphereServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudprovidervsphere.CloudProviderVsphere/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudProviderVsphereServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CloudProviderVsphere_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudprovidervsphere.CloudProviderVsphere",
	HandlerType: (*CloudProviderVsphereServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _CloudProviderVsphere_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloudprovidervsphere.proto",
}

func init() { proto.RegisterFile("cloudprovidervsphere.proto", fileDescriptor_b637d4c33cef7514) }

var fileDescriptor_b637d4c33cef7514 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0xc6, 0x33, 0x75, 0xcb, 0x17, 0x44, 0x3c, 0x3c, 0x0c, 0x12, 0x21, 0x12, 0xe1, 0x49, 0x62,
	0xbb, 0x75, 0xdc, 0xae, 0x4b, 0x2c, 0x1e, 0x22, 0xe8, 0x64, 0xce, 0x83, 0x04, 0x75, 0x6c, 0x9e,
	0x1a, 0xfb, 0xef, 0xf4, 0x97, 0xc6, 0xa8, 0xbb, 0x6d, 0x21, 0x04, 0xdd, 0xde, 0xf7, 0xbe, 0xf7,
	0xfb, 0xf4, 0xcd, 0x0c, 0x04, 0x79, 0xa9, 0x3a, 0xd9, 0x68, 0xd5, 0x17, 0x92, 0x74, 0xcf, 0xcd,
	0x1b, 0x69, 0x4a, 0x1a, 0xad, 0x5a, 0x85, 0xfe, 0x9c, 0x17, 0xad, 0xe1, 0x62, 0x5d, 0x70, 0xfb,
	0xa8, 0x24, 0x71, 0x4a, 0xef, 0x1d, 0x71, 0x8b, 0x02, 0x4e, 0xfa, 0x9c, 0xea, 0x96, 0xb4, 0xb0,
	0x42, 0x2b, 0xf6, 0xd2, 0x9d, 0xc4, 0x2b, 0x00, 0x99, 0xb5, 0xd9, 0x64, 0x1e, 0x0f, 0xe6, 0x41,
	0x27, 0xfa, 0xb4, 0xc0, 0x31, 0x51, 0xff, 0x8f, 0x40, 0x04, 0xa7, 0xce, 0x2a, 0x12, 0xf6, 0xe0,
	0x0c, 0x35, 0x06, 0x70, 0x2a, 0x6b, 0x36, 0x25, 0x0b, 0x27, 0xb4, 0x63, 0x2f, 0xdd, 0x6b, 0xbc,
	0x04, 0x2f, 0x93, 0x52, 0x13, 0x33, 0xb1, 0x70, 0x07, 0xf3, 0xbb, 0x61, 0xd2, 0xba, 0xae, 0x90,
	0x62, 0x31, 0xa6, 0x99, 0x3a, 0x7a, 0x86, 0xf3, 0x83, 0x95, 0x9b, 0x72, 0x8b, 0xb7, 0xe0, 0xd6,
	0x46, 0x09, 0x2b, 0xb4, 0xe3, 0xb3, 0x65, 0x90, 0xcc, 0x1e, 0xa3, 0x01, 0xd2, 0x71, 0x10, 0x7d,
	0x70, 0x49, 0x6b, 0xb5, 0x5b, 0x60, 0x14, 0x4b, 0x06, 0xff, 0xc1, 0x90, 0x9b, 0x89, 0x7c, 0x1a,
	0x49, 0x7c, 0x01, 0x6f, 0xff, 0x45, 0xbc, 0x99, 0x4f, 0xff, 0x7d, 0x0b, 0xc1, 0xf5, 0x9f, 0x73,
	0x4d, 0xb9, 0x8d, 0x8e, 0x56, 0xf7, 0x10, 0xe6, 0xaa, 0x4a, 0xfa, 0xea, 0x23, 0xd3, 0xf4, 0x93,
	0x49, 0x26, 0x68, 0x35, 0xfb, 0x5b, 0x1b, 0xeb, 0x75, 0x31, 0x3c, 0x8d, 0xbb, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3a, 0xd0, 0x05, 0x55, 0x38, 0x02, 0x00, 0x00,
}
